
/* 
* sepdp-misc.c
*
* Copyright (c) 2010, Zachary N J Peterson <znpeters@nps.edu>
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*     * Redistributions of source code must retain the above copyright
*       notice, this list of conditions and the following disclaimer.
*     * Redistributions in binary form must reproduce the above copyright
*       notice, this list of conditions and the following disclaimer in the
*       documentation and/or other materials provided with the distribution.
*     * Neither the name of the Naval Postgraduate School nor the
*       names of its contributors may be used to endorse or promote products
*       derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY ZACHARY N J PETERSON ``AS IS'' AND ANY
* EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL ZACHARY N J PETERSON BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



#include "sepdp.h"

void printhex(unsigned char *ptr, size_t size){

	int i = 0;
	for(i = 0; i < size; i++){
		printf("%02X", *ptr);
		ptr++;
	}
	printf("\n");
}

void sfree(void *ptr, size_t size){ memset(ptr, 0, size); free(ptr); ptr = NULL;}

/* generate_prf_f: an pseudo-random function (PRF) indexed on secret key W.
*  In this implementation, we use HMAC-SHA1
*/
unsigned char *generate_prf_f(unsigned char *key, unsigned int i, size_t *prf_result_size){

	unsigned char *prf_result = NULL;

	if(!key) return NULL;
	
	/* Allocate memory */
	if( ((prf_result = malloc(SHA_DIGEST_LENGTH)) == NULL)) goto cleanup;

	memset(prf_result, 0, SHA_DIGEST_LENGTH);

	/* Perform the HMAC on the index */
	if(!HMAC(EVP_sha1(), key, SEPDP_PRF_KEY_SIZE, (unsigned char *)&i, sizeof(unsigned int), 
		prf_result, (unsigned int *)prf_result_size)) goto cleanup;

	return prf_result;

cleanup:
	if(prf_result) sfree(prf_result, SHA_DIGEST_LENGTH);
	if(prf_result_size) *prf_result_size = 0;

	return NULL;	
}

/* key ki (generated by f_W() above), d blocks in the file, r indicies */
unsigned int *generate_prp_g(unsigned char *ki, size_t ki_size, unsigned int d, unsigned int r){

	unsigned char *prp_result = NULL;
	unsigned char *prp_input = NULL;
	AES_KEY aes_key;
	unsigned int index = 0;
	double result = 0.0;
	int x = 0, j = 0;
	unsigned int *indices = NULL;
	
	if(!ki || ki_size < SEPDP_PRP_KEY_SIZE) return NULL;

	/* Allocate memory */
	if( ((prp_result = malloc(SEPDP_PRP_KEY_SIZE)) == NULL)) goto cleanup;
	if( ((prp_input = malloc(SEPDP_PRP_KEY_SIZE)) == NULL)) goto cleanup;
	if( ((indices = malloc(r * sizeof(unsigned int))) == NULL)) goto cleanup;
	
	memset(prp_result, 0, SEPDP_PRP_KEY_SIZE);
	memset(prp_input, 0, SEPDP_PRP_KEY_SIZE);
	memset(&aes_key, 0, sizeof(AES_KEY));
	
	/* Setup the AES key */
	AES_set_encrypt_key(ki, SEPDP_PRP_KEY_SIZE * 8, &aes_key);
	
	/* Choose r blocks from 0 to d - 1 (file blocks) without replacement */
	for(x = 0; x < d && j < r; x++){
	
		/* Setup in the input buffer */
		memcpy(prp_input, &x, sizeof(int));
	
		/* Perform AES on the index */
		AES_encrypt(prp_input, prp_result, &aes_key);
	
		/* Turn the PRP result into a number */
		memcpy(&index, prp_result, sizeof(unsigned int));
	
		/* Make that number between 0 and 1 */
		result = ((double)index/(double)UINT_MAX);
	
		if( (d - x) * result < r - j){
			indices[j] = x;
			j++;
		}
	}
	
	/* Clear and free variables */
	if(prp_input) sfree(prp_input, SEPDP_PRP_KEY_SIZE);
	if(prp_result) sfree(prp_result, SEPDP_PRP_KEY_SIZE);
	memset(&aes_key, 0, sizeof(AES_KEY));
	
	return indices;

cleanup:
	if(prp_result) sfree(prp_result, SEPDP_PRP_KEY_SIZE);
	if(prp_input) sfree(prp_input, SEPDP_PRP_KEY_SIZE);
	if(indices) sfree(indices, (r * sizeof(unsigned int)));
	memset(&aes_key, 0, sizeof(AES_KEY));

	return NULL;
}

unsigned char *generate_H(unsigned char *c_i, size_t c_i_len, unsigned char **D, unsigned int r, size_t *vi_len){

	SHA_CTX ctx;
	unsigned char *vi = NULL; /* The token, aka hash result */
	int i = 0;

	if(!c_i || !D || !r) return NULL;
	
	if( ((vi = malloc(SHA_DIGEST_LENGTH)) == NULL)) goto cleanup;
	memset(vi, 0, SHA_DIGEST_LENGTH);
	
	if(!SHA1_Init(&ctx)) return NULL;
	
	/* Add c_i to the hash */
	if(!SHA1_Update(&ctx, c_i, c_i_len)) goto cleanup;
	
	for(i = 0; i < r; i++){
		if(!D[i]) goto cleanup;
		if(!SHA1_Update(&ctx, D[i], SEPDP_BLOCK_SIZE)) goto cleanup;
	}
	
	if(!SHA1_Final(vi, &ctx)) goto cleanup;
	
	*vi_len = SHA_DIGEST_LENGTH;
	return vi;
	
 cleanup:
	if(vi) sfree(vi, SHA_DIGEST_LENGTH);
	if(vi_len) *vi_len = 0;
	
	return NULL;
}

void destroy_sepdp_challenge(SEPDP_challenge *challenge){
	
	if(!challenge) return;
	if(challenge->i) challenge->i = 0;
	if(challenge->ki) sfree(challenge->ki, challenge->ki_size);
	if(challenge->ci) sfree(challenge->ci, challenge->ci_size);
	
	return;
}


int decrypt_and_verify_token(SEPDP_key *key, unsigned char *input, size_t input_len, unsigned char *plaintext, size_t *plaintext_len, unsigned char *authenticator, size_t authenticator_len){

	EVP_CIPHER_CTX ctx;
	EVP_CIPHER *cipher = NULL;
	unsigned char mac[EVP_MAX_MD_SIZE];
	size_t mac_size = EVP_MAX_MD_SIZE;
	int len;
	
	if(!key || !key->K || !input || !input_len || !plaintext || !plaintext_len || !authenticator || !authenticator_len) return 0; 
	
	OpenSSL_add_all_algorithms();
	memset(mac, 0, mac_size);
	
	/* Verify the HMAC-SHA1 */
	if(!HMAC(EVP_sha1(), key->K, key->K_size, input, input_len, mac, (unsigned int *)&mac_size)) goto cleanup;
	if(authenticator_len != mac_size) goto cleanup;
	if(memcmp(mac, authenticator, mac_size) != 0) goto cleanup;
	
	
	EVP_CIPHER_CTX_init(&ctx);
	switch(key->K_size){
		case 16:
			cipher = (EVP_CIPHER *)EVP_aes_128_cbc();
			break;
		case 24:
			cipher = (EVP_CIPHER *)EVP_aes_192_cbc();
			break;
		case 32:
			cipher = (EVP_CIPHER *)EVP_aes_256_cbc();
			break;
		default:
			return 0;
	}
	if(!EVP_DecryptInit(&ctx, cipher, key->K, NULL)) goto cleanup;
	
	*plaintext_len = 0;
	
	if(!EVP_DecryptUpdate(&ctx, plaintext, (int *)plaintext_len, input, input_len)) goto cleanup;
	EVP_DecryptFinal(&ctx, plaintext + *plaintext_len, &len);
	
	*plaintext_len += len;
	
	return 1;

cleanup:
	*plaintext_len = 0;

	return 0;
	
}

int encrypt_and_authentucate_token(SEPDP_key *key, unsigned char *input, size_t input_len, unsigned char *ciphertext, size_t *ciphertext_len, unsigned char *authenticator, size_t *authenticator_len){
	
	EVP_CIPHER_CTX ctx;
	EVP_CIPHER *cipher = NULL;
	int len;
	
	if(!key || !key->K || !input || !input_len || !ciphertext || !ciphertext_len || !authenticator || !authenticator_len) return 0;
	
	OpenSSL_add_all_algorithms();
	
	EVP_CIPHER_CTX_init(&ctx);
	switch(key->K_size){
		case 16:
			cipher = (EVP_CIPHER *)EVP_aes_128_cbc();
			break;
		case 24:
			cipher = (EVP_CIPHER *)EVP_aes_192_cbc();
			break;
		case 32:
			cipher = (EVP_CIPHER *)EVP_aes_256_cbc();
			break;
		default:
			return 0;
	}
	//TODO: Fix the NULL IV
	if(!EVP_EncryptInit(&ctx, cipher, key->K, NULL)) goto cleanup;

	*ciphertext_len = 0;
	
	if(!EVP_EncryptUpdate(&ctx, ciphertext, (int *)ciphertext_len, input, input_len)) goto cleanup;
	EVP_EncryptFinal(&ctx, ciphertext + *ciphertext_len, &len);
		
	*ciphertext_len += len;
	
	*authenticator_len = 0;
	/* Do the HMAC-SHA1 */
	//TODO: Add MAC key
	if(!HMAC(EVP_sha1(), key->K, key->K_size, ciphertext, *ciphertext_len,
		authenticator, (unsigned int *)authenticator_len)) goto cleanup;
	
	return 1;
	
cleanup:
	*ciphertext_len = 0;
	*authenticator_len = 0;
	
	return 0;
	
}

SEPDP_challenge *generate_sepdp_challenge(){
	
	SEPDP_challenge *challenge = NULL;
	
	if( ((challenge = malloc(sizeof(SEPDP_challenge))) == NULL)) goto cleanup;
	memset(challenge, 0, sizeof(SEPDP_challenge));
	
	return challenge;
	
 cleanup:
	if(challenge) destroy_sepdp_challenge(challenge);
	return NULL;
}

void destroy_sepdp_proof(SEPDP_proof *proof){

	if(!proof) return;
	if(proof->z) sfree(proof->z, proof->z_size);
	if(proof->token) sfree(proof->token, proof->token_size);
	proof->z_size = proof->token_size = 0;
	
	return;
}

SEPDP_proof *generate_sepdp_proof(){
	
	SEPDP_proof *proof = NULL;

	if( ((proof = malloc(sizeof(SEPDP_proof))) == NULL)) goto cleanup;
	memset(proof, 0, sizeof(SEPDP_proof));
	/* We don't allocate z because generate_H() allocates the memory for us */
	if( ((proof->token = malloc(SHA_DIGEST_LENGTH)) == NULL)) goto cleanup;
	memset(proof->token, 0, SHA_DIGEST_LENGTH);
	proof->token_size = SHA_DIGEST_LENGTH;
	
	return proof;
 cleanup:
	if(proof) destroy_sepdp_proof(proof);
	return NULL;
}
